name: 'release'
on: [ push, pull_request ]
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Validate gradlew'
        uses: gradle/actions/wrapper-validation@v4

      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'

      - name: 'Change permissions'
        run: chmod +x ./gradlew

      - name: 'Build plugin'
        run: ./gradlew --console plain --no-daemon --full-stacktrace check build

      - name: 'Release plugin'
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body: 'automated release at commit ${{ github.sha }}'
          files: 'build/dist/*.jar'